GET http://localhost:3000/tests/test

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/64e50d8c92573e3fa4180365

###
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "route test 3",
  "source_id": "ChIJlWcrdLg6WpMR9aiAqdCC11g",
  "destination_id": "ChIJbVO40fs6WpMRjLuC-AD-i4E"
}

#### Places from Google Maps

### Get first place_id
GET http://localhost:3000/places?text=Simpsons - SHIGS 706 Bl. D, Loja 35 - Asa Sul, Brasilia - Federal District

### Get second place_id
GET http://localhost:3000/places?text=Brasília Shopping - Asa Norte, Brasilia - Federal District

### Get directions between two places
GET http://localhost:3000/directions?originId=ChIJlWcrdLg6WpMR9aiAqdCC11g&destinationId=ChIJbVO40fs6WpMRjLuC-AD-i4E